---
- hosts: apache
  connection: ssh
  gather_facts: no
  tasks:
   - name: Install Apache package
     yum: pkg=httpd state=installed update_cache=true
   - name: Restart HTTPD
     service: name=httpd state=started
   - name: add a cron job to the node
     cron: minute="0" hour="1" job="ls -a"
   - name: create the user call tomcat
     group: name=tomcat gid=1234 state=present
   - name: create the user call tomcat
     user: name=tomcat shell=/bin/bash
   - name : copy the files to remote server
     copy: src=/home/ubuntu/execute.sh dest=/home/ec2-user/execute.sh owner=apache group=apache mode=0755
   - name: Execute script
     shell: /home/ec2-user/execute.sh
   - name: find the date in hosts
     raw: /usr/bin/uptime